apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  company: xxx
  dept: xxx
  project: xxx
  group_email: xxx
  user_group_email: xxx