# accesscontextmanager API
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: "none"
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: xxx # kpt-set: ${env}-accesscontextmanager
  namespace: xxx # kpt-set: ${company}-${dept}-${project}
spec:
  projectRef:
    name: xxx # kpt-set: ${env}-project
    namespace: xxx # kpt-set: ${company}-${dept}-${project}
  resourceID: accesscontextmanager.googleapis.com
---
apiVersion: accesscontextmanager.cnrm.cloud.google.com/v1beta1
kind: AccessContextManagerServicePerimeter
metadata:
  name: devstgbridgesp
  namespace: ${company}-${dept}-${project} # kpt-set: ${company}-${dept}-${project}
spec:
  title: ${company}-${dept}-${project}-dev-stg-bridge-serviceperimeter # kpt-set: ${company}-${dept}-${project}-dev-stg-bridge-serviceperimeter
  perimeterType: PERIMETER_TYPE_BRIDGE
  accessPolicyRef:
    external: accessPolicies/272037973676
  status:
    resources:
      - projectRef:
          name: dev-project
          namespace: xxx # kpt-set: ${company}-${dept}-${project}
      - projectRef:
          name: stg-project
          namespace: xxx # kpt-set: ${company}-${dept}-${project}